### ISSUE TITLE
openlog(): corrupted memory reference

### ISSUE THREAD

**Issue by vitek** [luaposix/luaposix#282]
`openlog()` itself internally stores pointer to `ident` argument. But we don't have any guarantee  that this pointer is alive after `openlog()` finished.

It seems to me that `Popenlog()` should hold local `ident` copy.

**Comment by gvvaughan** [comment]
Thanks for the bug report.  And also for the suggested fix, though I'd like to try to find a thread-safe solution before merging your fix...

**Comment by vitek** [comment]
Syslog operations itself are thread-safe at least as implemented in glibc and uclibc. I've updated my PR

**Comment by gvvaughan** [comment]
Thanks for the update, and sorry for the radio silence.

Your update is still not thread safe though, because two threads calling the function at the same time will cause a race condition on the static variable declaration.  I'll try to find some time this week to implement a fix without this issue.

**Comment by gvvaughan** [comment]
Actually, I take back my last comment.  Looking at the SUSv3 specs, your patch was correct after all, and I was too quick to dismiss it.  Sorry about that.

Nonetheless, I think saving a copy of the string in the Lua Registry is a simpler approach than strduping a copy into a static variable with raw C.  I've done some light testing to check this approach behaves correctly on Linux.  Please let me know if you have any further trouble with it.
